### PR TITLE
Added Backtesting of a Trading Strategy 

### PR DESCRIPTION
**Pull request by Akshat111111**
The given code uses a trading strategy and historical Bitcoin data to do a financial analysis. It simulates trading choices, uses an engulfing candlestick pattern as a technical trading technique, collects Bitcoin price data via an API, and computes performance measures such as Sharpe ratio, average daily return, and Value at Risk (VaR).

A percentage of the original investment is set aside for trading using the candlestick pattern as part of this technique. The simulation monitors changes in portfolio values over time and contrasts them with fluctuations in the price of Bitcoin. Performance measures like VaR and Sharpe ratio are computed to evaluate the risk-adjusted returns of the strategy.

### CODE REVIEW

**Comment by Akshat111111** [comment]
Ref- Adding Backtesting code #21

**Review by cantaro86 — COMMENTED** [review]
Apart from the fact that this notebook does not deal with numerical methods or financial modeling. Still, it could be an interesting topic from the trading and backtesting side.
However, the backtesting in this notebook does not appear to be done rigorously. I say "seems" because the text is completely missing, so I don't know exactly what you're doing. There are no comments, there's not even a title. The final part of the notebook is totally useless.

How long did it take you to make this notebook? 20 minutes? I'm sorry but the quality is very low and cannot be compared with the other notebooks in the repository.

If you are still interested, I advise you to rephrase everything and use a more rigorous and reader-friendly approach. 
Only after that, I will review the notebook again and we can work together on making it interesting for the reader

**Comment by Akshat111111** [comment]
Sure, For the beginner friendly approach I will add the comments with proper explanation.

**Comment by cantaro86** [comment]
@Akshat111111  it seems you are looking to contribute to open-source repositories.  
I understand that. But you should understand that you cannot just propose a random notebook far from the topics and the style of this repository.  
All the notebooks here are mathematically rigorous, there are references to scientific papers, and the level is very deep in the presented topics.
Adding a few comments is not enough. 

If you really want to publish your work in this repo, then I'll let you create a new PR with your work in the **final** version. But if your intentions are not serious, then I recommend you create your own repository where you can discuss the topics you like in the style you like.
I'm closing this PR for now.

**Pull request closed without merging**
